name: Build Tox Dual-Core Version

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64]
        include:
          - goarch: amd64
            arch_name: 64
          - goarch: arm64
            arch_name: arm64-v8a
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'
          check-latest: true

      - name: Build
        run: |
          export CGO_ENABLED=0
          go build -v -trimpath -ldflags="-s -w" -o tox ./main.go

      - name: Prepare Package
        run: |
          mkdir -p release
          cp tox release/
          # 从 example 文件夹拷贝资源文件
          cp example/geoip.dat release/ || true
          cp example/geosite.dat release/ || true
          cp example/config.json release/ || true
          cp example/dns.json release/ || true
          cp example/route.json release/ || true
          cp example/custom_outbound.json release/ || true
          cp example/custom_inbound.json release/ || true
          cd release
          zip -r ../Tox-linux-${{ matrix.arch_name }}.zip .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Tox-linux-${{ matrix.arch_name }}
          path: Tox-linux-${{ matrix.arch_name }}.zip

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: Tox-linux-${{ matrix.arch_name }}.zip
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
